"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";

type Tab="stats"|"users"|"courses"|"payments"|"operations";
interface Stats{totalUsers:number;totalCourses:number;totalEnrollments:number;questionCount:number;paymentTotal:number}
interface User{id:number;email:string;nickname:string;role:string}
interface Course{id:number;title:string;category:string;instructor:{nickname:string}|null;enrollmentCount:number}
interface Payment{id:number;order_id:string;amount:number;status:string;method:string|null;course_title:string;email:string;nickname:string;created_at:string}
interface RefundRequest{id:number;reason:string;status:string;created_at:string;reviewed_at:string|null;payment_id:number;amount:number;payment_status:string;course_title:string;requester_nickname:string;requester_email:string;reviewer_nickname:string|null}
interface Operations{jobs:Array<{id:number;job_name:string;status:string;message:string;created_at:string}>;webhooks:Array<{id:number;provider:string;event_type:string;status:string;created_at:string}>;payments:{pendingPayments:number;failedPayments:number;cancelledPayments:number}}

const labels:Record<Tab,string>={stats:"통계",users:"사용자",courses:"강의",payments:"결제·환불",operations:"운영 상태"};

export default function AdminPage(){
  const router=useRouter(); const [tab,setTab]=useState<Tab>("stats"); const [stats,setStats]=useState<Stats|null>(null); const [users,setUsers]=useState<User[]>([]); const [courses,setCourses]=useState<Course[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [refunds,setRefunds]=useState<RefundRequest[]>([]); const [operations,setOperations]=useState<Operations|null>(null); const [message,setMessage]=useState("");
  useEffect(()=>{if(localStorage.getItem("role")!=="admin"){router.push("/dashboard");return;} api<Stats>("/admin/stats").then(setStats).catch(()=>router.push("/dashboard"));},[router]);
  function changeTab(next:Tab){setTab(next);if(next==="users")api<{users:User[]}>("/admin/users").then((d)=>setUsers(d.users));if(next==="courses")api<{courses:Course[]}>("/admin/courses").then((d)=>setCourses(d.courses));if(next==="payments"){api<{payments:Payment[]}>("/admin/payments").then((d)=>setPayments(d.payments));api<{refunds:RefundRequest[]}>("/admin/refunds").then((d)=>setRefunds(d.refunds));}if(next==="operations")api<Operations>("/admin/operations").then(setOperations);}
  async function changeRole(id:number,role:string){await api(`/admin/users/${id}/role`,{method:"PATCH",body:JSON.stringify({role})});setUsers((list)=>list.map((u)=>u.id===id?{...u,role}:u));setMessage("역할을 변경했습니다.");}
  async function deleteCourse(course: Course){if(!confirm(`"${course.title}" 강의와 관련 학습 데이터를 삭제할까요?`))return;await api(`/admin/courses/${course.id}`,{method:"DELETE"});setCourses((list)=>list.filter((c)=>c.id!==course.id));}
  async function cancelPayment(id:number){const reason=prompt("환불 사유를 입력하세요","관리자 환불");if(!reason)return;await api(`/admin/payments/${id}/cancel`,{method:"POST",body:JSON.stringify({reason})});setPayments((list)=>list.map((p)=>p.id===id?{...p,status:"cancelled"}:p));setMessage("결제 취소가 완료되었습니다.");}
  async function reviewRefund(refundId:number, action:"approve"|"reject"){await api(`/admin/refunds/${refundId}`,{method:"PATCH",body:JSON.stringify({action})});const [paymentsRes,refundsRes]=await Promise.all([api<{payments:Payment[]}>("/admin/payments"),api<{refunds:RefundRequest[]}>("/admin/refunds")]);setPayments(paymentsRes.payments);setRefunds(refundsRes.refunds);setMessage(action==="approve"?"환불을 승인했습니다.":"환불을 거절했습니다.");}
  return <div className="min-h-screen bg-white"><header className="bg-zinc-950 px-5 py-14 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-extrabold tracking-[3px] text-[#00C471]">ADMIN CONSOLE</p><h1 className="mt-3 text-4xl font-extrabold">플랫폼 운영</h1><p className="mt-2 text-zinc-400">회원, 강의, 결제, 외부 연동을 한 곳에서 관리합니다.</p></div></header><main className="mx-auto max-w-6xl px-5 py-8">{message&&<p className="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-600">{message}</p>}<div className="mb-8 flex gap-2 overflow-x-auto pb-2">{(Object.keys(labels) as Tab[]).map((item)=><button key={item} onClick={()=>changeTab(item)} className={`shrink-0 rounded-full px-5 py-2 text-sm font-bold ${tab===item?"bg-[#00C471] text-white":"bg-zinc-100 text-zinc-600"}`}>{labels[item]}</button>)}</div>
  {tab==="stats"&&stats&&<section className="grid grid-cols-2 gap-4 lg:grid-cols-5">{[["사용자",stats.totalUsers],["강의",stats.totalCourses],["수강",stats.totalEnrollments],["질문",stats.questionCount],["총 매출",`${stats.paymentTotal.toLocaleString()}원`]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-zinc-50 p-6"><p className="text-xs font-bold text-zinc-500">{label}</p><strong className="mt-2 block text-2xl">{value}</strong></div>)}</section>}
  {tab==="users"&&<section className="space-y-2">{users.map((u)=><div key={u.id} className="flex flex-col gap-3 rounded-2xl bg-zinc-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div><strong>{u.nickname}</strong><p className="text-sm text-zinc-500">{u.email}</p></div><select value={u.role} onChange={(e)=>changeRole(u.id,e.target.value)} className="rounded-lg border bg-white px-3 py-2 text-sm"><option value="student">학생</option><option value="instructor">강사</option><option value="admin">관리자</option></select></div>)}</section>}
  {tab==="courses"&&<section className="space-y-2">{courses.map((c)=><div key={c.id} onClick={()=>router.push(`/course/${c.id}`)} className="flex cursor-pointer items-center justify-between rounded-2xl bg-zinc-50 p-5 transition hover:bg-zinc-100"><div><div className="flex items-center gap-2"><strong>{c.title}</strong><span className="rounded-full bg-white px-2 py-0.5 text-[11px] font-semibold text-zinc-500">#{c.id}</span></div><p className="text-sm text-zinc-500">{c.category} · {c.instructor?.nickname||"강사 미지정"} · 수강 {c.enrollmentCount}명</p><p className="mt-1 text-xs text-zinc-400">클릭하면 강의 상세로 이동합니다.</p></div><button onClick={(e)=>{e.stopPropagation();deleteCourse(c);}} className="text-sm font-bold text-rose-600">삭제</button></div>)}</section>}
  {tab==="payments"&&<section className="space-y-8"><div><h2 className="mb-3 text-lg font-extrabold">환불 신청</h2><div className="space-y-3">{refunds.map((refund)=><div key={refund.id} className="rounded-2xl bg-zinc-50 p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><strong>{refund.course_title}</strong><p className="text-sm text-zinc-500">{refund.requester_nickname} · {refund.requester_email}</p></div><span className="text-sm font-bold text-zinc-600">{refund.status}</span></div><p className="mt-3 text-sm text-zinc-700">{refund.reason}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>reviewRefund(refund.id,"approve")} disabled={refund.status!=="requested"} className="rounded-full bg-[#00C471] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">승인</button><button onClick={()=>reviewRefund(refund.id,"reject")} disabled={refund.status!=="requested"} className="rounded-full bg-rose-50 px-4 py-2 text-sm font-bold text-rose-600 disabled:opacity-40">거절</button></div></div>)}{refunds.length===0&&<p className="rounded-2xl bg-zinc-50 p-6 text-sm text-zinc-500">환불 신청이 없습니다.</p>}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr className="border-b text-zinc-500"><th className="p-3">주문</th><th>구매자</th><th>강의</th><th>금액</th><th>상태</th><th>관리</th></tr></thead><tbody>{payments.map((p)=><tr key={p.id} className="border-b"><td className="p-3 font-mono text-xs">{p.order_id}</td><td>{p.nickname}<br/><span className="text-xs text-zinc-500">{p.email}</span></td><td>{p.course_title}</td><td>{p.amount.toLocaleString()}원</td><td>{p.status}</td><td>{p.status==="completed"&&<button onClick={()=>cancelPayment(p.id)} className="rounded-full bg-rose-50 px-3 py-1 text-rose-600">환불</button>}</td></tr>)}</tbody></table></div></section>}
  {tab==="operations"&&operations&&<section className="grid gap-6 lg:grid-cols-2"><div><h2 className="mb-3 text-lg font-extrabold">최근 배치</h2><div className="space-y-2">{operations.jobs.map((job)=><div key={job.id} className="rounded-xl bg-zinc-50 p-4 text-sm"><div className="flex justify-between"><strong>{job.job_name}</strong><span className={job.status==="success"?"text-green-600":"text-rose-600"}>{job.status}</span></div><p className="mt-1 text-zinc-500">{job.message}</p></div>)}</div></div><div><h2 className="mb-3 text-lg font-extrabold">Webhook 이벤트</h2><div className="space-y-2">{operations.webhooks.map((event)=><div key={event.id} className="rounded-xl bg-zinc-50 p-4 text-sm"><div className="flex justify-between"><strong>{event.provider} · {event.event_type}</strong><span>{event.status}</span></div></div>)}</div></div></section>}
  </main></div>;
}
