"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { api } from "@/lib/api";

interface LessonLink { id:number; title:string; order:number; duration:number; watched_seconds?:number }
interface Lesson extends LessonLink { course_id:number; course_title:string; video_url:string; watched_seconds:number; previousLesson:LessonLink|null; nextLesson:LessonLink|null; curriculum:LessonLink[] }

export default function LearnPage(){
  const {id}=useParams(); const router=useRouter(); const [lesson,setLesson]=useState<Lesson|null>(null); const [watched,setWatched]=useState(0); const watchedRef=useRef(0); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const [studying,setStudying]=useState(false);
  useEffect(()=>{if(!localStorage.getItem("token")){router.push("/login");return;}api<Lesson>(`/lessons/${id}`).then((data)=>{setLesson(data);setWatched(data.watched_seconds||0);watchedRef.current=data.watched_seconds||0;}).catch((error)=>setMessage(error instanceof Error?error.message:"불러오기 실패"));},[id,router]);
  useEffect(()=>{watchedRef.current=watched;},[watched]);
  useEffect(()=>{if(!lesson||!studying)return;const timer=window.setInterval(()=>{if(document.visibilityState==="visible")setWatched((value)=>Math.min(value+5,lesson.duration||value+5));},5000);return()=>window.clearInterval(timer);},[lesson,studying]);
  const save=useCallback(async(silent=false)=>{if(!lesson)return;setSaving(true);try{await api("/progress",{method:"POST",body:JSON.stringify({lessonId:lesson.id,watchedSeconds:watchedRef.current})});if(!silent)setMessage("학습 진도를 저장했습니다.");}catch(error){if(!silent)setMessage(error instanceof Error?error.message:"저장 실패");}finally{setSaving(false);}},[lesson]);
  useEffect(()=>{if(!lesson)return;const timer=window.setInterval(()=>save(true),30000);const onHide=()=>save(true);window.addEventListener("pagehide",onHide);return()=>{window.clearInterval(timer);window.removeEventListener("pagehide",onHide);save(true);};},[lesson,save]);
  async function move(target:LessonLink|null){if(!target)return;await save(true);router.push(`/learn/${target.id}`);}
  if(!lesson)return <div className="mx-auto max-w-5xl p-8 text-sm text-zinc-500">{message||"강의를 불러오는 중입니다."}</div>;
  const youtubeId=lesson.video_url.match(/[?&]v=([^&]+)/)?.[1]; const progress=lesson.duration?Math.min(100,Math.round((watched/lesson.duration)*100)):0;
  return <div className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 lg:grid-cols-[1fr_320px]"><main><button onClick={()=>router.push(`/course/${lesson.course_id}`)} className="mb-4 text-sm text-zinc-400">← 강의 상세</button><p className="text-sm text-[#FF385C]">{lesson.course_title}</p><h1 className="mb-5 mt-2 text-2xl font-extrabold">{lesson.title}</h1><div className="aspect-video overflow-hidden rounded-2xl bg-black">{youtubeId?<iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${youtubeId}?enablejsapi=1`} title={lesson.title} allowFullScreen/>:<div className="grid h-full place-items-center text-zinc-500">등록된 영상이 없습니다.</div>}</div><section className="mt-5 rounded-2xl bg-zinc-900 p-5"><div className="flex items-center justify-between text-sm"><span>학습 진행률</span><strong className={progress>=90?"text-green-400":"text-[#FF385C]"}>{progress>=90?"완료":`${progress}%`}</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-zinc-700"><div className="h-full bg-[#FF385C] transition-all" style={{width:`${progress}%`}}/></div><p className="mt-3 text-xs text-zinc-500">학습 시작 상태에서 페이지가 활성화된 시간만 누적하며 30초마다 자동 저장합니다. 90% 이상이면 완료 처리됩니다.</p><div className="mt-5 flex flex-wrap items-center gap-3"><button onClick={()=>setStudying((value)=>!value)} className={`rounded-full px-5 py-2 text-sm font-bold ${studying?"bg-amber-400 text-zinc-950":"bg-green-500 text-white"}`}>{studying?"학습 일시정지":"학습 시작"}</button><button onClick={()=>move(lesson.previousLesson)} disabled={!lesson.previousLesson} className="rounded-full border border-zinc-700 px-5 py-2 text-sm disabled:opacity-30">이전 강의</button><button onClick={()=>save(false)} className="rounded-full bg-zinc-700 px-5 py-2 text-sm">{saving?"저장 중":"지금 저장"}</button><button onClick={()=>move(lesson.nextLesson)} disabled={!lesson.nextLesson} className="rounded-full bg-[#FF385C] px-5 py-2 text-sm font-bold disabled:opacity-30">다음 강의</button>{message&&<span className="text-sm text-zinc-400">{message}</span>}</div></section></main><aside className="h-fit rounded-2xl bg-zinc-900 p-4 lg:sticky lg:top-24"><h2 className="mb-4 font-extrabold">커리큘럼</h2><div className="space-y-1">{lesson.curriculum.map((item)=>{const complete=!!item.duration&&(item.watched_seconds||0)>=item.duration*0.9;return <button key={item.id} onClick={()=>move(item)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left text-sm ${item.id===lesson.id?"bg-[#FF385C]":"hover:bg-zinc-800"}`}><span className="w-6 text-xs">{complete?"✓":item.order}</span><span className="flex-1">{item.title}</span><span className="text-xs opacity-60">{Math.ceil(item.duration/60)}분</span></button>})}</div></aside></div></div>;
}
